### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by IwanVosloo** [diopib/jollof_rice#1]
I just noticed that the actual source code (recipe) is missing.

**Comment by shante665** [comment]
I am more than happy to help with the awesome recipe to the Nigerian Jollof, however I cannot say this is the same as the one from Senegal. After searching high and low. [This recipe](http://www.dobbyssignature.com/2013/12/nigerian-party-jollof-rice-recipe.html) describes how we cook the Open source jollof the Nigerian way :)

**Comment by diopib** [comment]
What Will do is actually submit both source code (the Senegalese one and the Nigerian one) :)

**Comment by IwanVosloo** [comment]
I don't think it matters which recipe we have. Any one is a start. Surely we can adapt from there and configure for regional preferences? (Unfortunately I am the ONE person who has NO clue how to even start...)

**Comment by diopib** [comment]
@IwanVosloo both recipes are now (finally) pushed :)
